aws:
  paramstore:
    region: 'ap-northeast-2'
    enabled: true
    prefix: /config
    profile-separator: _
    name: bookery

spring:
  application:
    name: bookery
  config:
    import: "aws-parameterstore:"
    activate:
      on-profile: default
  h2:
    console:
      enabled: true
      path: /h2

  devtools:
    livereload:
      enabled: false

  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8

  datasource:
    url: jdbc:h2:mem:bookery;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
