spring:
  h2:
    console:
      enabled: true
      path: /h2

  devtools:
    livereload:
      enabled: false

  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8

  datasource:
    url: jdbc:h2:mem:bookery;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
